# Generated by Django 3.1.4 on 2020-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201212_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(auto_created=True),
        ),
    ]
